const conferenceRouter = require("./conference");
const gameRouter = require("./game");
const gameMatchesRouter = require("./gameMatches");
const matchRouter = require("./match");
const playerRouter = require("./player");
const playerGamesRouter = require("./playerGames");
const playerRolesRouter = require("./playerRoles");
const roleRouter = require("./role");
const securityRouter = require("./security");
const teamRouter = require("./team");
const orgRouter = require("./org");
const orgMatchesRouter = require("./orgMatches");
const orgPlayersRouter = require("./orgPlayers");
const userRouter = require("./user");
const weekRouter = require("./week");

module.exports = (router) => {
    conferenceRouter(router);
    gameRouter(router);
    gameMatchesRouter(router);
    matchRouter(router);
    playerRouter(router);
    playerGamesRouter(router);
    playerRolesRouter(router);
    roleRouter(router);
    securityRouter(router);
    teamRouter(router);
    orgRouter(router);
    orgMatchesRouter(router);
    orgPlayersRouter(router);
    userRouter(router);
    weekRouter(router);
};
